### ISSUE TITLE
Relicensing

### ISSUE THREAD

**Issue by jereksel** [jereksel/Bucket#199]
I would like to relicense LibreSubstratum to GPLv3 or Apache 2.0 (I'm still on the fence about it). Because of legal reasons I have to ask contributors for their agreement. Please reply to this issue with "I agree" if you agree or "I don't agree" if not.

Current contributors:
@dimqua 
@Poussinou

**Comment by dimqua** [comment]
I agree.

**Comment by TheComputerGuy96** [comment]
I agree (if GPLv3)

**Comment by Poussinou** [comment]
I agree

And I prefer GPLv3 because it's a stronger copyleft license if you want my opinion.
