### ISSUE TITLE
Error with swift dark and Whatsapp build

### ISSUE THREAD

**Issue by beatstick** [jereksel/Bucket#238]
When I try to build and activate whatsapp with the swift dark skin I get the following error:

/data/user/0/com.jereksel.libresubstratum/cache/1516483117033-0/AndroidManifest.xml:2: Tag <manifest> attribute package has invalid character ','.

I'm using swift dark 14 .4

bucket (from f-droid is used to install)

Android 7.1 (crdroid 3.82 motog falcon) 

What could be the problem?

**Comment by jereksel** [comment]
Will be fixed in next release: #211
