### ISSUE TITLE
Add maxSdkVersion to Manifest

### ISSUE THREAD

**Issue by Shadow53** [jereksel/Bucket#243]
I am currently able to install Bucket on my Android Oreo 8.1 phone, only for Bucket to inform me that it does not support my version of Android. I'm not an Android developer but, from what I understand, I think you want to include a `maxSdkVersion` line in your `build.gradle` that indicates the latest version of Android that Bucket is compatible with, so that app stores don't display the app to users who can't run it.

https://developer.android.com/guide/topics/manifest/uses-sdk-element.html

> Future versions of Android (beyond Android 2.0.1) will no longer check or enforce the `maxSdkVersion` attribute during installation or re-validation. **Google Play will continue to use the attribute as a filter**, however, when presenting users with applications available for download.

The also applies to F-Droid (where I downloaded Bucket), which filters apps based on `maxSdkVersion` since 2014: https://www.f-droid.org/en/2014/04/08/client-0-63-released.html

**Comment by jereksel** [comment]
To be honest, I didn't knew that this attribute exists. (Un) fortunately Bucket now supports rooted Oreo (at least in beta), so this attribute won't be needed.
